# Makefile

BUILD_DIR       = $(shell pwd)

BIN_DIR         = bin
commitinfo.sh   := $(wildcard bin/commitinfo.sh)

HTML_DIR        = html
ALL_RSC         := $(wildcard html/*.rsc html/*/*.rsc)
GLOB_RSC        := $(wildcard html/AM-GlobalFunc.rsc)

DATE            ?= $(shell (date '+%T %d.%m.%Y'))
DTSTAMP         ?= $(shell (date '+%Y%d%m%H%M%S'))
VERSION         ?= $(shell git symbolic-ref --short HEAD 2>/dev/null)/$(shell git rev-list --count HEAD 2>/dev/null)/$(shell git rev-parse --short=8 HEAD 2>/dev/null)
RUN_OWNER       := $(shell whoami 2>/dev/null)
COMM_REPO		:= $(shell git rev-parse --show-toplevel | rev | cut -d/ -f1 | rev 2>/dev/nul)
COMM_BRANCH		:= $(shell git symbolic-ref --short HEAD 2>/dev/null)

COMM_TAG := $(shell git rev-list --abbrev-commit --tags --max-count=1)
# `2>/dev/null` suppress errors and `|| true` suppress the error codes.
TAG := $(shell git describe --abbrev=0 --tags ${COMM_TAG} 2>/dev/null || true)
# here we strip the version prefix
TAG_VERS :=$(TAG:v%=%)
# get the latest commit hash in the short form
COMM_HASH := $(shell git rev-parse --short=8 HEAD 2>/dev/null) # Get short commit hash
#COMMIT := $(shell git rev-parse --short HEAD)
# get the latest commit date in the form of YYYYmmdd
COMM_DATE := $(shell git log -1 --format=%cd --date=format:"%Y%m%d%H%M")
ifneq ($(COMM_HASH), $(COMM_TAG))
    TAG_VERS :=$(TAG_VERS)-next-$(COMM_HASH)-$(COMM_DATE)
endif
ifeq ($(TAG_VERS), )
    TAG_VERS :=$(COMM_HASH)-$(COMM_DATE)
endif
ifneq ($(shell git status --porcelain), )
    TAG_VERS :=$(TAG_VERS)-dirty
endif

COMMIT_ID       := $(VERSION)
COMM_INFO       := $(shell echo -e "Autocommit in repo: $(COMM_REPO), generated by owner: $(RUN_OWNER), in $(DATE)." 2>/dev/null)

export BUILD_DIR BIN_DIR HTML_DIR DATE DTSTAMP VERSION COMMIT_ID COMM_TAG COMM_HASH COMM_INFO

.ONESHELL:
SHELL := /bin/bash
.DEFAULT_GOAL := run

export BUILD_DIR BIN_DIR HTML_DIR DATE DTSTAMP VERSION COMMIT_ID COMM_TAG COMM_HASH COMM_INFO

include $(BUILD_DIR)/.config/config.mk

.PHONY: run check notify test

run: check
	@echo "[run] start main flow"
    # ...
	@echo "[run] done"

check:
	@bash bin/check_repo.sh

notify:
	@bash bin/notify_telegram.sh "manual notify from make"

test:
	@bash -n bin/check_repo.sh
	@bash -n bin/notify_telegram.sh
	@echo "syntax ok"


.DEFAULT_GOAL := all
.PHONY: all checksums git-check commitinfo clean

define run-git =
    git $@
endef

all: checksums git-check commitinfo

checksums: checksums.json

checksums.json: bin/checksums.sh $(ALL_RSC)
	bin/checksums.sh > html/tmp/$@

gitcheck: $(BUILD_DIR)
	cd $ && 
	@if git diff --quiet && git diff --cached --quiet && [ -z "$$(git ls-files --others --exclude-standard)" ]; then \
		echo "The first checks have been passed, the repo seems to be clean... But... Still, let's check a little more!"; \
	    git add . && ; \ 
		if [[ -n git status --porcelain ]]; then \
			echo "Uncommitted changes detected! Commit it..."; \
#			git commit -m "$(COMM_INFO)"; \
#			git push; \
    	    exit 1; \
		else \
			echo "repo clean"; \
		fi \
	else \
		@echo "Warning: Uncommitted changes detected! Go to autocommit steps..."; \
#		git branch -v; \
#		git commit -am "$(COMM_INFO)"; \
#		git push; \
	fi


#@if [ -n "$$(git diff --quiet)" ] && [ -n "$$(git diff --cached --quiet)" ] && [ -n "$$(git ls-files --others --exclude-standard)" ]; then \
#[ -n "$$(git status --porcelain)" ]

check-uncommitted: 
		@if [ -n "$$(git diff --quiet)" ] && [ -n "$$(git diff --cached --quiet)" ] && [ -n "$$(git ls-files --others --exclude-standard)" ]; then \
			echo "Warning: Uncommitted changes detected! Go to autocommit steps..."; \
		else \
	    	echo "The first checks have been passed, the repo seems to be clean... But... Still, let's check a little more!"; \
	   		if git status --porcelain; then \
				echo "Repository is clean (no uncommitted or untracked changes). Exit 0."; \
				exit 0; \
			else \
				echo "Error! Git status is not porcelain! Check it mannualy. Exit 1."; \
				exit 1; \
			fi \
		fi


#    if [[ -n "`$(rungit) status --porcelain`" ]];: then \
	echo "Warning: Uncommitted changes detected! Go to autocmmit..."; \
        git commit -m "$(COMM_INFO)"; \
	git push origin $(COMM_BANCH); \
    else \
	echo "Repository is clean (no uncommitted or untracked changes). Exit 0."; \
	exit 0; \
    fi

commitinfo: $(commitinfo.sh)

.PHONY: $(commitinfo.sh)
$(commitinfo.sh): $(GLOB_RSC)
		$(commitinfo.sh) $< > $<~
		mv $<~ $<


clean:
		git checkout HEAD -- .

#	rm -f $(HTML) checksums.json
#	make -C contrib/ clean
