
export DRY_RUN      ?= 0

export DATE         ?= $(shell (date '+%T %d.%m.%Y'))
export DTSTAMP_FMT	?= "+%Y%m%d%H%M"
export DTSTAMP      ?= $(shell (date $(DTSTAMP_FMT)))
export VERSION      ?= $(shell git symbolic-ref --short HEAD 2>/dev/null)/$(shell git rev-list --count HEAD 2>/dev/null)/$(shell git rev-parse --short=8 HEAD 2>/dev/null)
export RUN_OWNER    := $(shell whoami 2>/dev/null)
export COMM_REPO	:= $(shell git rev-parse --show-toplevel | rev | cut -d/ -f1 | rev 2>/dev/nul)
export COMM_BRANCH	:= $(shell git symbolic-ref --short HEAD 2>/dev/null)
export COMMIT_ID    := $(VERSION)
export COMM_INFO    := $(shell echo -e "Autocommit in repo: $(COMM_REPO), generated by owner: $(RUN_OWNER), in $(DATE)." 2>/dev/null)

export BOT_TOKEN    ?= "undefined"
export CHAT_ID      ?= "undefined"
export TGDisableWebPagePreview ?= "True"
export TGParseMode  ?= "html"
